services:
  - type: web
    name: ecosphere
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/database.sqlite
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: ecosphere-data
      mountPath: /var/data
      sizeGB: 1
